### PR TITLE
[PR]: YouTube Embedding

### PR DESCRIPTION
**Pull request by jimbrig**
Issue #18

### CODE REVIEW

**Comment by jimbrig** [comment]
image

**Review by phoward38 — COMMENTED** [review]
@jimbrig lgtm

**Review by phoward38 — COMMENTED** [review]
@jimbrig lgtm

**Review by phoward38 — APPROVED** [review]

**Review by phoward38 — APPROVED** [review]

**Comment by jimbrig** [comment]
> @jimbrig lgtm

what's lgtm? lol

**Pull request merged**
